### ISSUE TITLE
Typo: mercury Academy, Mission 3

### ISSUE THREAD

**Issue by thedemogamer** [ReentryGame/ReentryBugsAndWiki#94] opened 2020-07-02 02:20 UTC
# Typo

## Which program did you find a flaw in?
Mercury 
## Which section
Academy
## Where did you find it
Mission 3 - Checklists and Atlas, first dialog. 
## What's the wrong word or phrase?
“Launc Vehicle”
## What should it be?
“Launch Vehicle”

**Comment by sundhaug92** [comment] 2020-09-04 13:59
Closed as dupe of #79 and #64

**Closed as completed by sundhaug92** 2020-09-04 13:59 UTC
Labels: typo, academy, mercury, tmp-label-mission-typo-fixes
